# fastai setup  file locations example.

#  Stackoverflow -- installing fastai.

fastai library import failure on ipython on conda
Ask Question
Asked 9 months ago
Viewed 169 times

0


When trying to import fastai library within ipython on a conda setup, it fails with the following error (irrespective of Windows or Linux). On anaconda prompt it exists without any message:

"ImportError: dlopen: cannot load any more object with static TLS In [2]: QXcbConnection: XCB error: 145 (Unknown), sequence: 171, resource id: 0, major code: 139 (Unknown), minor code: 20"

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-af1f7fb2dc52> in <module>()
----> 1 import fastai

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/__init__.py in <module>()
----> 1 from .basic_train import *
      2 from .callback import *
      3 from .callbacks import *
      4 from .core import *
      5 from .basic_data import *

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py in <module>()
      1 "Provides basic training and validation with `Learner`"
----> 2 from .torch_core import *
      3 from .basic_data import *
      4 from .callback import *
      5

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/torch_core.py in <module>()
      1 "Utility functions to help deal with tensors"
----> 2 from .imports.torch import *
      3 from .core import *
      4
      5 AffineMatrix = Tensor

~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/imports/__init__.py in <module>()
      1 from .core import *
----> 2 from .torch import *
